site_name: WaferMap
site_description: "wfmap Documentation"
repo_url: https://github.com/xlhaw/wfmap/
site_url: https://www.wfmap.ml/
edit_uri: ./edit/master/docs
repo_name: "xlhaw/wfmap"
copyright: Copyright &copy; 2017 - 2022 Leon Xiao
site_author: Leon Xiao

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Getting Started: index.md
  - Data Preparation: data.md
  - Example Gallery: generated/gallery
  - GUI Application: gui.md
  - API Reference: docstrings.md
  - ChangeLogs: changelog.md
  - Repository: "https://github.com/xlhaw/wfmap/"


extra:
  analytics:
    provider: google
    property: G-8FQ3JVBZ1X
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xlhaw
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xlhaw
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/xlhaw
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/xlhaw
    - icon: fontawesome/solid/paper-plane
      link: mailto:<i@xlhaw.com>

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - attr_list
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji

use_directory_urls: True
plugins:
  - search
  - mkdocstrings:
      enable_inventory: false
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
      watch:
        - wfmap
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - gallery:
      conf_script: docs/gallery_conf.py 
      examples_dirs:
        - docs/examples 
      gallery_dirs:
        - docs/generated/gallery 
      backreferences_dir: docs/generated/backreferences
      show_memory: False


extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/mkdocstrings.css
